### ISSUE TITLE
Crash On World Gen

### ISSUE THREAD

**Issue by SammyMcBlu** [Real-Gecko/BornToBe#2]
Here's the crash report:

[crash-2018-06-16_21.41.26-server.txt](https://github.com/Real-Gecko/BornToBe/files/2108643/crash-2018-06-16_21.41.26-server.txt)

I'm not sure exactly why it crashed but I had this mod installed on a save game and it worked fine. Then I made a new world and it crashed. The only relatable mods I have that may interfere with this one are Configurable Villager Doors to Ratio, MoVillages, and Villager Trades.

**Comment by Real-Gecko** [comment]
What's your exact setup?

**Comment by Flytre** [comment]
I'm getting the same thing... without Villager Doors Ratio or MoVillages

**Comment by Real-Gecko** [comment]
Upload the full MC log after crash.

**Comment by Reassembly** [comment]
Just had (almost) the same crash - not many relevant mods in common with the OP aside from Villager Trade Tables. Didn't happen for me when generating a new world, but when approaching a village for the first time in my current world. Same NullPointerException at the same line in the same class, though.

Crash log: https://paste.dimdev.org/aduxixerus.mccrash

**Comment by ghost** [comment]
I just had the same thing as Reassembly and the OP, including the line 60 crash. I won't bother with the log, you've got 2. I'm doing the whittle down from a million modpack design and I have a stupid number of mods. Some of which are proving to be stupid. ;)

**Comment by ghost** [comment]
maybe run Minecraft with fewer mods?

**Comment by uhmbye** [comment]
Having the same issue, I've removed Born in a Barn, Snow Village, etc. Still having the issue afterwards. I think it's a problem with Born to Be and not a conflict.

**Comment by crazyirishwrencher** [comment]
[crash-2018-12-11_02.07.54-server.txt](https://github.com/Real-Gecko/BornToBe/files/2672305/crash-2018-12-11_02.07.54-server.txt)
Same. Crashed upon village approach.

**Comment by Real-Gecko** [comment]
For those who're still interested in having non vanilla villagers from VTT read [this comment](https://github.com/Real-Gecko/BornToBe/issues/4#issuecomment-495148438).
